task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', 'segm']

num_classes: 1
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/shuangy/DEIMv2/data/coco/images
    ann_file: /home/shuangy/DEIMv2/data/coco/annotations/train2017.json
    return_masks: True
    return_weak_geometry: True
    use_category2label: True
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/shuangy/DEIMv2/data/coco/images
    ann_file: /home/shuangy/DEIMv2/data/coco/annotations/test2017.json
    return_masks: True
    return_weak_geometry: True
    use_category2label: True
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
