__include__: [
  '../dataset/custom.yml',
  '../ecdet/ecdet_s.yml',
  'ecseg.yml',
]

output_dir: outputs/ecseg_s_0.003

ViTAdapter:
  name: ecseg_vitt
  weights_path: ecvits/ecseg_vitt.pth

optimizer:
  type: AdamW

  params:
    -
      # except norm/bn/bias in backbone
      params: '^(?=.*.backbone)(?!.*(?:norm|bn|bias)).*$'
      lr: 0.000015
    -
      # including all norm/bn/bias in backbone
      params: '^(?=.*.backbone)(?=.*(?:norm|bn|bias)).*$'
      lr: 0.000015
      weight_decay: 0.
    -
      # including all norm/bn/bias except for the backbone
      params: '^(?!.*\.backbone)(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0003
  betas: [0.9, 0.999]
  weight_decay: 0.0001