__include__: [
  '../dataset/hrsid_detection.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/optimizer.yml',
  '../base/deimv2.yml'
]

output_dir: ./outputs/deimv2_dinov3_s_hrsid

DEIM:
  backbone: DINOv3STAs

DINOv3STAs:
  name: vit_tiny
  embed_dim: 192
  weights_path: ./ckpts/vitt_distill.pt
  interaction_indexes: [3, 7, 11]
  num_heads: 3

HybridEncoder:
  in_channels: [192, 192, 192]
  depth_mult: 0.67
  expansion: 0.34
  hidden_dim: 192
  dim_feedforward: 512

DEIMTransformer:
  feat_channels: [192, 192, 192]
  hidden_dim: 192
  dim_feedforward: 512
  num_layers: 4
  eval_idx: -1

eval_spatial_size: [800, 800]

optimizer:
  type: AdamW
  params:
    - {params: '^(?=.*.dinov3)(?!.*(?:norm|bn|bias)).*$', lr: 0.000025}
    - {params: '^(?=.*.dinov3)(?=.*(?:norm|bn|bias)).*$', lr: 0.000025, weight_decay: 0.}
    - {params: '^(?=.*(?:sta|encoder|decoder))(?=.*(?:norm|bn|bias)).*$', weight_decay: 0.}
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0.0001

epoches: 132
flat_epoch: 64
no_aug_epoch: 12

train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [800, 800]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 120
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  collate_fn:
    base_size: 800
    base_size_repeat: ~
    mixup_prob: 0.0
    copyblend_prob: 0.0

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [800, 800]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: Normalize, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}

DEIMCriterion:
  matcher:
    change_matcher: True
    iou_order_alpha: 4.0
    matcher_change_epoch: 100
